export enum CreatePostEnum {
  CREATE_POST = 'CREATE_POST',
  CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS',
  CREATE_POST_ERROR = 'CREATE_POST_ERROR',
}

export enum ListPostsEnum {
  LIST_POSTS = 'LIST_POSTS',
  LIST_POSTS_SUCCESS = 'LIST_POSTS_SUCCESS',
  LIST_POSTS_ERROR = 'LIST_POSTS_ERROR',
}

export enum GetPostByIdEnum {
  GET_POST_BY_ID = 'GET_POST_BY_ID',
  GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS',
  GET_POST_BY_ID_ERROR = 'GET_POST_BY_ID_ERROR',
}

export enum DeletePostEnum {
  DELETE_POST = 'DELETE_POST',
  DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS',
  DELETE_POST_ERROR = 'DELETE_POST_ERROR',
}

export enum CreateLikeEnum {
  CREATE_LIKE = 'CREATE_LIKE',
  CREATE_LIKE_SUCCESS = 'CREATE_LIKE_SUCCESS',
  CREATE_LIKE_ERROR = 'CREATE_LIKE_ERROR',
}

export enum DeleteLikeEnum {
  DELETE_LIKE = 'DELETE_LIKE',
  DELETE_LIKE_SUCCESS = 'DELETE_LIKE_SUCCESS',
  DELETE_LIKE_ERROR = 'DELETE_LIKE_ERROR',
}

export enum CreateCommentEnum {
  CREATE_COMMENT = 'CREATE_COMMENT',
  CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR',
}

export enum DeleteCommentEnum {
  DELETE_COMMENT = 'DELETE_COMMENT',
  DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR',
}

export enum CreateUserEnum {
  CREATE_USER = 'CREATE_USER',
  CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS',
  CREATE_USER_ERROR = 'CREATE_USER_ERROR',
}

export enum ListUsersEnum {
  LIST_USERS = 'LIST_USERS',
  LIST_USERS_SUCCESS = 'LIST_USERS_SUCCESS',
  LIST_USERS_ERROR = 'LIST_USERS_ERROR',
}

export enum GetUserByIdEnum {
  GET_USER_BY_ID = 'GET_USER_BY_ID',
  GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_ERROR = 'GET_USER_BY_ID_ERROR',
}

export enum LoginUserEnum {
  LOGIN_USER = 'LOGIN_USER',
  LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR = 'LOGIN_USER_ERROR',
  LOGOUT = 'LOGOUT',
}

export enum DeleteUserEnum {
  DELETE_USER = 'DELETE_USER',
  DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS',
  DELETE_USER_ERROR = 'DELETE_USER_ERROR',
}

export enum AssignRoleToUserEnum {
  ASSIGN_ROLE = 'ASSIGN_ROLE',
  ASSIGN_ROLE_SUCCESS = 'ASSIGN_ROLE_SUCCESS',
  ASSIGN_ROLE_ERROR = 'ASSIGN_ROLE_ERROR',
}
