name: React and Express app deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout React App
        uses: actions/checkout@v2

      - name: Install and build React app
        run: cd client && npm install && npm run build

      - name: Deploy React app
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: client/build # The folder the action should deploy.

      - name: Checkout Express App
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: photos-custom-directives #Must be unique in Heroku
          heroku_email: shadedvoxels@gmail.com
          appdir: server
        env:
          HD_JWT_SECRET_KEY: ${{secrets.HD_JWT_SECRET_KEY}}
          HD_MONGO_URI: ${{secrets.HD_MONGO_URI}}
