name: React and Express app deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout React App
        uses: actions/checkout@v1

      - name: Install and build React app
        run: cd client && npm install && npm run build-prod

      - name: Deploy React app
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: client/build # The folder the action should deploy.
